name: base
channels:
    - conda-forge
dependencies:
    - python=3.12
    - natcap.invest==3.14.1
    - gdal
    - pygeoprocessing
    - pandas
    - taskgraph
    - matplotlib
    - cxx-compiler
    - jupyter
    - requests
    - make
    - flask
    - google-cloud-storage
